
site_name: Viktor Bengs â€“ Personal Homepage
theme:
  name: material
nav:
  - Home: index.md
  - Circulum Vitae: cv.md
  - Publications: publications.md
  - Talks: talks.md
  - Data Science: dsskills.md
  - Teaching: teaching.md
